# Generated by Django 2.2 on 2021-01-04 11:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschemacolumn',
            name='end_value',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dataschemacolumn',
            name='start_value',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=20)),
                ('file', models.FileField(default='error.csv', upload_to='')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_generator.DataSchema')),
            ],
        ),
    ]
