# Generated by Django 3.1.5 on 2021-01-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0003_dataset_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='task_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataschemacolumn',
            name='end_value',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='dataschemacolumn',
            name='start_value',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
